In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[8.0, 5.3, 6.7], [2.4, 5.6, 9.1]])
print(b)

[[8.  5.3 6.7]
 [2.4 5.6 9.1]]


In [5]:
# get dimension
a.ndim

1

In [9]:
a.shape

(3,)

In [8]:
b.size

6

In [10]:
a.dtype

dtype('int32')

In [12]:
a = np.array([1,2,3], dtype='int8')
a.dtype

dtype('int8')

In [16]:
a.itemsize

1

In [18]:
a = np.array([1,2,3], dtype='int32')
a.itemsize  # bytes

4

In [19]:
#total size
a.size*a.itemsize

12

In [20]:
a.nbytes

12

In [4]:
import numpy as np
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14], [2,3,4,5,6,7,8]])
c[1,4]

12

In [5]:
# fancy indexing [startindex:endindex:step]
c[0, 1:6:2]

array([2, 4, 6])

In [6]:
c[0, 1:-1:2]

array([2, 4, 6])

In [42]:
c[2,:] = 5
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [ 5,  5,  5,  5,  5,  5,  5]])

In [47]:
c[:,2]=[4,3,7]
c

array([[ 1,  2,  4,  4,  5,  6,  7],
       [ 8,  9,  3, 11, 12, 13, 14],
       [ 5,  5,  7,  5,  5,  5,  5]])

In [51]:
d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [52]:
d[0,1,1]

4

In [54]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

### initialize types of arrariesm

In [57]:
# all zero matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
# all one matrix
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [62]:
# any other numbers
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [64]:
# any other numbers (full like)
np.full(c.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [65]:
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [66]:
# radom decimal numbers
np.random.rand(4,2)

array([[0.69354299, 0.32459261],
       [0.68455333, 0.28412748],
       [0.00490625, 0.32463648],
       [0.23249791, 0.06217686]])

In [68]:
np.random.random_sample(a.shape)

array([0.43650598, 0.7667794 , 0.35728697])

In [69]:
# random integers
np.random.randint(4)

1

In [70]:
np.random.randint(4, size=(3,3))

array([[3, 1, 0],
       [1, 0, 2],
       [0, 0, 1]])

In [73]:
np.random.randint(4,8, size=(3,3))

array([[6, 5, 6],
       [4, 7, 5],
       [4, 4, 4]])

In [75]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
# repeat array
arr = [[1,2,3],[4,5,6]]
r = np.repeat(arr,3)
r

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [83]:
r = np.repeat(arr,3, axis=0)
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [84]:
r = np.repeat(arr,3, axis=1)
r

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

In [87]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [92]:
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [93]:
output[1:4, 1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### copying arrays

In [97]:
a=np.array([1,2,3])
b = a  # b points to the same thing as a
b[1] =100
print(b)
print(a)

[  1 100   3]
[  1 100   3]


In [100]:
a=np.array([1,2,3])
b = a.copy() 
b[1] = 100
print(a)

[1 2 3]


### mathmatics

In [104]:
a=np.array([1,2,3,4])
print(a)
print(a+2)

[1 2 3 4]
[3 4 5 6]


In [105]:
b = np.array([2,2,2,2])
a+b

array([3, 4, 5, 6])

In [106]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

https://docs.scipy.org/doc/numpy/reference/routines.math.html

### Linear algebra

In [110]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [112]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [117]:
# find determinant
c =  np.identity(3)
np.linalg.det(c)

1.0

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

### statistics`m

In [120]:
s = np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
np.min(s)

1

In [122]:
np.max(s, axis=1)

array([3, 6])

In [123]:
np.sum(s)

21

In [124]:
np.sum(s, axis=0)

array([5, 7, 9])

### reorgnizing arrays

In [130]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
after = before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [131]:
before.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [133]:
# vertical stacking vectors
v1 =  np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])              

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [134]:
np.vstack([v1,v2,v2])    

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [136]:
# horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [138]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### load data from file 

In [ ]:
f = np.genfromtxt('xxx.txt', delimiter = ',')
f = f.astype('int32')

### Boolean masking and advanced indexing

In [148]:
s > 3

array([[False, False, False],
       [ True,  True,  True]])

In [149]:
s[s>3]

array([4, 5, 6])

In [153]:
# indexing using a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [154]:
np.any(s>2)

True

In [157]:
np.any(s>3, axis=1)

array([False,  True])

In [161]:
((s<2) & (s>4))

array([[False, False, False],
       [False, False, False]])

In [162]:
(~((s<2) & (s>4)))

array([[ True,  True,  True],
       [ True,  True,  True]])

In [4]:
import numpy as np
data_ndarray = np.array([10, 20, 30])
print(data_ndarray)

[10 20 30]


In [7]:
import csv
import numpy as np

# import nyc_taxi.csv as a list of lists
f = open("nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

# start writing your code below this comment
taxi=np.array(converted_taxi_list)
print(taxi)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


In [9]:
row_0=taxi[0]
rows_391_to_500=taxi[391:501]
row_21_column_5=taxi[21, 5]

In [10]:
columns_1_4_7=taxi[:, [1,4,7]]
row_99_columns_5_to_8=taxi[99, 5:9]
rows_100_to_200_column_14=taxi[100:201, 14]

In [11]:
fare_amount = taxi[:,9]
fees_amount = taxi[:,10]
fare_and_fees = fare_amount + fees_amount

In [12]:
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour
trip_mph = trip_distance_miles/trip_length_hours
print(trip_mph)

[37.11340206 38.58157895 31.27222982 ... 22.29907867 42.41551247
 36.90473407]


In [13]:
mph_min = trip_mph.min()
mph_max=trip_mph.max()
mph_mean=trip_mph.mean()

In [14]:
taxi_first_five = taxi[:5]
fare_components = taxi_first_five[:, 9:13]
fare_sums = fare_components.sum(axis = 1)
fare_totals = taxi_first_five[:,13]
print(fare_totals)
print(fare_sums)

[69.99 54.3  37.8  32.76 18.8 ]
[69.99 54.3  37.8  32.76 18.8 ]


#### boolean indexing

In [15]:
import numpy as np
taxi = np.genfromtxt('nyc_taxis.csv', delimiter=',')
taxi_shape = taxi.shape
print(taxi_shape)

(89561, 15)


In [18]:
import numpy as np
taxi=np.genfromtxt('nyc_taxis.csv', delimiter=',', skip_header = 1)
# skip_header parameter accepts an integer, the number of rows from the start of the file to skip

taxi_shape = taxi.shape
print(taxi)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


In [20]:
a = np.array([1, 2, 3, 4, 5])
b = np.array(["blue", "blue", "red", "blue"])
c = np.array([80.0, 103.4, 96.9, 200.3])
a_bool =a < 3
b_bool =b =='blue'
c_bool =c>100
print(a_bool, b_bool, c_bool)

[ True  True False False False] [ True  True False  True] [False  True False  True]


In [27]:
pickup_month = taxi[:,1]

january_bool = pickup_month == 1
january = pickup_month[january_bool]
january_rides = january.shape  # returns a tuple

february_bool = pickup_month == 2
february = pickup_month[february_bool]
february_rides = february.shape[0]

march_bool = pickup_month == 3
march = pickup_month[march_bool]
march_rides = march.shape[0]

print(january_rides)
print(february_rides)

(13481,)
13333


In [28]:
tip_amount = taxi[:,12]
tip_bool = tip_amount > 50
top_tips = taxi[tip_bool, 5:14]

In [29]:
taxi_modified = taxi.copy()
taxi_modified[28214, 5] = 1
taxi_modified[:,0] = 16
taxi_modified[1800:1802, 7] = taxi_modified[:,7].mean()

In [30]:
taxi_copy = taxi.copy()
total_amount = taxi_copy[:,13]
total_amount[total_amount < 0] = 0

In [33]:
taxi_modified = taxi.copy()

# create a new column filled with `0`.
zeros = np.zeros([taxi_modified.shape[0], 1])
taxi_modified = np.concatenate([taxi, zeros], axis=1)
print(taxi_modified)
taxi_modified[taxi_modified[:,5]==2, 15]=1
taxi_modified[taxi_modified[:,5]==3, 15]=1
taxi_modified[taxi_modified[:,5]==5, 15]=1

[[2.016e+03 1.000e+00 1.000e+00 ... 6.999e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 5.430e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 3.780e+01 2.000e+00 0.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 6.334e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 4.475e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 5.484e+01 2.000e+00 0.000e+00]]


In [36]:
# calculate how many trips had Airports 2, 3, 5 as their destination
jfk=taxi[taxi[:, 6]==2, :]
jfk_count=jfk.shape[0]
laguardia=taxi[taxi[:, 6]==3, :]
laguardia_count=laguardia.shape[0]
newark=taxi[taxi[:, 6]==5, :]
newark_count=newark.shape[0]
print(jfk_count, laguardia_count, newark_count)

11832 16602 63


In [37]:
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)
cleaned_taxi=taxi[trip_mph<100, :]
mean_distance=cleaned_taxi[:,7].mean()
mean_length=cleaned_taxi[:,8].mean()
mean_total_amount=cleaned_taxi[:,13].mean()

In [ ]:
print(ones)
print(zeros)
print() # creates a space in our output

print(ones.shape)
print(zeros.shape)
print()

zeros_2d = np.expand_dims(zeros,axis=1)
print(zeros_2d)
print(zeros_2d.shape)
print()
print('\n')
combined = np.concatenate([ones,zeros_2d],axis=1)
print(combined)
print()

# the `trip_mph` variable is still available from the
# previous screen
trip_mph_2d=np.expand_dims(trip_mph, axis=1)
taxi=np.concatenate([taxi, trip_mph_2d], axis=1)
print(taxi)

In [ ]:
# sort n array based on last col
sorted_order = np.argsort(taxi[:,15])
taxi_sorted = taxi[sorted_order]
print(taxi_sorted)

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a[a > 2] = 9
print(a)

[1 2 9 9 9]


In [5]:
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

c[c[:,1] > 2, 1] = 99
c

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7, 99,  9]])